---
title: "Recent insecticide resistance literature for rotations and wos papers"

# output: pdf_document:

output: word_document
bibliography: library.bib
csl: biomed-central.csl

---


#### Record of which publications show mortality vs concentration for RR SR SS
[@Gould2018, @Bourguet2000, @Mallett1989]
Dose response plots for RR,SR and SS showing change in effective resistance with increasing concentration are shown in a large number of publications but no one has turned them around the other way and related them to time.
  
#### Gassmann 2009 fitness costs in Bt - Good
A review of 65 experimental studies of the costs of resistance to Bt toxins [@Gassmann2009] found fitness costs in around half. From 16 studies looking at fitness components they found that in 26% of comparisons fitness of rs was lower than that of ss indicating dominance of cost greater than zero. In four studies there was evidence that costs were dominant i.e. the fitness of the rs was equal to the rr. Based on these they suggest that for species with no data a recessive fitness cost of 25% be assumed for resistance to Bt.

Suppplemental table 4 shows that four studies and eight fitness components indicate dominant costs of resistance. Studies 6,8,13 and 16.


"Nonrecessive costs strongly favor decreased r allele frequency through selection against rs in refuges, despite selection on Bt crops favoring rr individuals. Accordingly, the dominance of fitness costs is critical, just as the dominance of resistance is critical."

  
#### Andow 2015 resistance to Bt in corn rootworm - Good
Good accessible description e.g. of high dose strategy.
[@Andow2015]

The different experiences with resistance to Bt maize in two different moth pests points to the importance of these population genetic parameters. Resistance has become a problem for the Western corn rootworm where resistance is not recessive, there are minimal costs of resistance and low dispersal. In contrast resistance has yet to become a problem for the European corn borer where resistance is recessive, there are higher costs of resistance and low dispersal. [@Andow2015]

(originally from tweet : https://twitter.com/alimanfoo/status/1014120657540575232)


High-dose in high-dose strategy means that all heterozgotes are killed and resistance is effectively recessive. But also defined operationally as 25 x the amount of toxin needed to kill 99.99% of a susceptible population. 

#### Tabshnik2017 review of insecticide resistance to Bt crops, another good accessible summary
In a review of insect resistance to engineered plants they found that 0 out of 17 studies where resistance has been detected met the high-dose standard, in contrast where susceptibility remains, 9 out of 13 cases did not meet the high-dose standards. [@Tabashnik2017]. Points to low doses prompting evolution of resistance through reduced dominance. One example also suggests that having larger refuges can compensate for the high-dose standard not being met.

Concludes that the main lesson overall is that abundant refuges delay resistance to transgeni crops. In a public health context this points to the importance of understanding the proportion of insect vector populations that are exposed to insecticide interventions. It also warns of a potential increase in the evolution of resistance as intervention coverage is increased for example as a part of malaria elimination efforts.


#### Gressel 2017
High doses likely to select for resistance conferred by single genes of major effect whereas low doses can allow the accumulation of many genes of minor effect. [@Gressel2017].
  
#### Onstad 2001 rootworm model used to inform EPA  
Dominance of resistance was the most important parameter influencing evolution of resistance. If fully recessive (dominance 0) resistance not reached in 99 years, if fully dominant, resistance took just 2–5 years when refuges were 5% to 30% [@Onstad2001].  
  
#### Carriere 2018
Measured the decline in frequencies of alleles conferring resistance to Bt toxins in pink bollworm raised in the absence of the toxin. By comparing observed and simulated changes in resistance they estimated that costs of resistance were between 14% and 36%. For one allele the results pointed to the costs being completely recessive and the other they suggested a small cost of 2% for the heterozygote suggesting a dominance of cost of 0.08.

The fitness costs of resistance to Bt toxins within the pink bollworm have been shown to be sufficient to reduce the frequency of resistance in the absence of the toxin but they are almost completely recessive. [@Carriere2018]

"When the frequency of resistance declines, selection against resistance alleles with recessive costs also declines because homozygous-resistant individuals become relatively rare. By contrast, selection against alleles with non-recessive costs is higher because heterozygotes remain relatively abundant. Accordingly, alleles inducing non-recessive costs should be eliminated at a faster rate than alleles inducing recessive costs." cites Falconer81 Intro to quantitative genetics.

"However, non-recessive costs of Bt resistance affecting fitness components seem relatively common. In 16 studies evaluating the dominance of costs, the percentage of non-recessive costs was 43% for development time, 21% for survival and 0% for growth rate.[@Gassmann2009]"
  

#### Tabashnik2005 Delayed resistance to Bt cotton
Monitoring of resistance in the pink bollworm to Bt toxins from transgenic plants showed no increase in resistance for 8 years despite widespread planting [@Tabashnik2005]. Combined experimental and simulation results suggest this could be due to untreated refuges, resistance being completely recessive, low resistance restoration, and resistance costs. A simulation showed that with 50% refuges and resistance restoration set to 0.6, fitness costs greater than 38% were required for resistance to decrease.

(Note that they assume that costs as well as resistance are recessive). 

(We could try to produce something similar to Fig 2 in [@Tabashnik2005].)
 
  
#### Carriere 2001
Simple equation for whether resistance is expected to increase or decrease based on benefits and costs [@Carriere2001]. Be good for us to indicated how our model differs from this.

They found some similar things to us, e.g. resistance not increasing when dominance of resistance low and dominance of cost high.


#### Glunt 2018 Impact of temperature on insecticide toxicity.
Relevant to window of selection. 
In arabiensis & funestus with deltamethrin, generally mortalities higher when temperatures either higher or lower than standard. The difference between resistant and susceptible mortality is generally less, suggesting that the window of selection may be lower outside of standard lab conditions [@Glunt2018]. 


#### Hackett 2016 model of resistance to transgenic crops
Similar results to us on the importance of dominance of resistance and cost :
"the most significant constraint upon model behaviour is the dominance of the resistant phenotype, with greater dominance decreasing Bt usage. For a given level of dominance of resistance, the type and dominance of any fitness costs may relax these constraints, allowing for larger areas of Bt crop [smaller refuges to control resistance evolution]" [@Hackett2016]


#### Helps 2017 model of effect of high dose on resistance selection in agriculture
*to do* look at this again. [@Helps2017] across a wide range of demographics etc.
for wos
"One management strategy that has long been advocated is the application of insecticides at the maximum permitted dose. This has been found, under some circumstances, to be able to prevent the resistance allele frequency from increasing. However this approach may, under different circumstances, lead to rapid selection for resistance to the insecticide."

"It is demonstrated that with high immigration resistance can be suppressed. This suppression however, is rarely lost if the insecticide dose is reduced, and is absent altogether when individuals move from the treated population back into an untreated population. Reducing the dose of insecticide often resulted in slower development of resistance, except where the population combined a high influx of less resis- tant individuals into the treated population, a recessive resistance gene and a high efficacy, in which case reducing the dose of insecticide could result in faster selection for resistance."

"Because insecticides can have adverse impacts on non-target organisms, regulators have to ensure that the maximum permitted dose on the product la- bel is also the minimum dose required to achieve effective control ( Anon, 2012 ). The process of determining that dose was described by Finney (1993) , as follows. In farm crops, there are many fac- tors that affect the level of control achieved with any given dose. Hence, if dose-response experiments are repeated across many sites and seasons, many different dose-response curves result. For practical purposes, the label recommended dose is usually set at the level which gives a high level of control in a high proportion of circumstances. Finney suggested 80–90% control in 80–90% of field experiments as a typical aim, although higher levels of control may be required for insect pests, for example, to prevent insect contam- ination in horticultural crops. There are two consequences of this process of determining the full label dose which are relevant to the analysis presented here. Firstly, the label dose will not be set at a level which gives 100% control, even of sensitive strains, since, as previously mentioned, this is not the aim of the maximum al- lowed dose specified on a product label. Hence, the modelling ap- proach presented assumes that it is not possible to drive resistant strains to extinction by insecticide treatment, within the range of doses permitted."

#### Immaraju 1990 Field Evaluation of Insecticide Rotation and Mixtures as Strategies for Citrus Thrips
[@Immaraju1990]

#### Kleinschmidt 2018 Implications of insecticide resistance for malaria vector control
WHO study
[@Kleinschmidt2018]

#### mbepera 2017 susceptibility higher in older anopheles
[@mbepera2017]



#### Curtis 1993 good quotes and references about rotations.
*todo, look at more*
It covers the oncheriasis control program which is taken by some to be evidence in favour of rotations.
Fig 3 & 4 is lab data comparing sequence & rotation, very similar to our plots, I should definitely cite it. [@Curtis1993]

Curtis cites how his 1987 work has already included effect of modifier genes, and shows it here in Fig 6.
"Supporters of prearranged rotations usually tacitly or explicitly assume that the general fitness due to resistance genes will improve if they are exposed to selection for many generations. Curtis (1987) simulated the behaviour of a modifer gene which could have this effect and found that it would only have an appreciable influence if one allowed resistance gene frequencies to become very high before switching insecticides.""

"One possible objection to the reactive system is that it requires an efficient and comprehensive system for testing for resistance to avoid ‘overshooting’ and
getting stuck as in the dotted line in Fig. 6. However, running a prearranged
rotation without a monitoring system would mean that one would have no way
of knowing if the system was still working."

#### Venter2017 Benchmarking insecticide resistance intensity bioassays
The operational effect of insecticides will depend on doses and the resistance phenotypes of mosquitoes. Resistance intensity assays are a way of qauntifying this, here intensity assays are related to the resistance phenotypes of lab strains with characterised resistance mechanisms. 
probably cite this in windows paper.

#### lopezmonroy2018
Relates the frequency and intensity of pyr resistance in aedes to the frequency of kdr genes. Useful in translating between our modelling work and field measurements of resistance.

#### Mbida2018 nets collected from the field against kdr resistant mosquitoes
Shows that field collected nets kill all susceptible mosquitoes but low proportions of field collected mosquitoes. Genotyping the field collected mosquitoes exposed to the field collected nets (Table 4) showed that 7-35 % of the surviviors had the susceptible kdr allele and none of those killed had the resistance allele. This demonstrates that the nets are within the window of selection and will be selecting for kdr resistance.

#### Denholm1992
In an agricultural context points out that theory suggests that rotations and sequences should be equivalent.
"Despite theoretical misgivings regarding the benefit of alternations, the prevalence of this tactic in existing strategies on cotton and elsewhere demonstrates its intuitive appeal and relative ease of implementation." [@Denholm1992]

#### Matowo2015 rapid increase in Bendiocarb resistance following IRS, support for our modelling approach
There was a sharp decrease in mortality in An. gambiae s.l. exposed to bendiocarb (carbamate) from 84% in November 2011 to 31% in December 2012 after two rounds of bendiocarb-based indoor residual spraying (IRS). Anopheles gambiae s.l. remained susceptible to pirimiphos-methyl
(organophosphate). Bendiocarb-based IRS did not lead to the reversion of pyrethroid resistance.
We could maybe model this. They have some data on various gene frequencies.

#### Gullberg2011 Selection of Resistant Bacteria at Very Low Antibiotic Concentrations
Shows windows of selection for antibiotic resistance in bacteria and how these extend to very low concentrations where the antibiotics are not effective. [@Gullberg2011]




## References
<!-- now auto created here-->